/**
 * exportTerraform.ts — S4 (export-only) strategy.
 *
 * Downloads the compiled Terraform as a self-contained main.tf, entirely in the
 * browser. No backend call, no credentials, no Mapdoc involvement: the purest
 * "less dependent on Mapdoc" path (see CLOUD_BUILDER_TRUST_ARCHITECTURE.md §4 S4).
 * The user runs it themselves wherever they have terraform + cloud credentials.
 */

const RUN_INSTRUCTIONS = [
  '# Generated by Mapdoc. Self-contained Terraform — runs anywhere with terraform + cloud credentials.',
  '# Run it yourself (no Mapdoc involvement):',
  '#   terraform init',
  '#   terraform plan      # review the changes',
  '#   terraform apply     # supply any variables it declares (e.g. var.db_password)',
  '',
  '',
].join('\n');

export function downloadTerraform(hcl: string, name = 'main'): void {
  const blob = new Blob([RUN_INSTRUCTIONS + hcl], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${name}.tf`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}
